spring.application.name=POS

# ==========DATA SOURCE==========
spring.datasource.url=jdbc:mysql://localhost:3306/test_pos?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=1100
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==========JPA/HIBERNATE==========
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ==========SERVER==========
server.port=8081
server.servlet.context-path=/api/v1

# ==========LOGGING==========
logging.level.root=INFO
logging.level.com.devstack=DEBUG
logging.file.name=app.log

# ==========PROFILE==========
spring.profiles.active=dev